spring:
  #Application Properties
  application:
    name: movie-ticket-booking-system-api

  #Datasource Properties
  datasource:
    url: "${MYSQL_URL:jdbc:mysql://localhost:3306/mdb?createDatabaseIfNotExist=true}"
    username: "${MYSQL_USERNAME:root}"
    password: "${MYSQL_PWD:root}"

    hikari:
      data-source-properties:
        serverTimezone: UTC

  #JPA Details
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      jdbc:
        time_zone: UTC
    properties:
      hibernate:
        default_batch_fetch_size: 100

  # Mail Configuration (Gmail SMTP)
  mail:
    host: smtp.gmail.com
    port: 587
    username: "${MAIL_USERNAME:your_email@gmail.com}"
    password: "${MAIL_PWD:your_app_password}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Internal Configuration
app:

  company:
    name: "${APP_COMPANY_NAME:CinePass}"

  token:
    secret: "${TOKEN_SECRET:xEZeHOjDYg2qcL0T4Wll6vxyhChpCN8uvqLMhJ5Fi+8=}" #Only for testing and development mode
    access-duration: "${TOKEN_ACCESS_DURATION:5}" #in minutes
    refresh-duration: "${TOKEN_REFRESH_DURATION:1440}" #in minutes 24*60

#Context-path
server:
  servlet:
    context-path: /api/v1

# Razorpay Configuration
razorpay:
  key:
    id: "${RAZORPAY_KEY_ID:rzp_test_SdQB3dXy2AYPRE}"
    secret: "${RAZORPAY_KEY_SECRET:mRw6D0ey1WUxvm0JnOYxINne}"

# Twilio Configuration for SMS
twilio:
  account-sid: "${TWILIO_ACCOUNT_SID:dummy_sid}"
  auth-token: "${TWILIO_AUTH_TOKEN:dummy_token}"
  phone-number: "${TWILIO_PHONE_NUMBER:dummy_phone_number}"