Spring:
  #APPLICATION PROPERTIES
  application:
    name: movie-ticket-booking-system-api
  datasource:
    driver-class name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mdb?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true